server:
  port: 8002

spring:
  redis:
    database: 0
    host: tianfudadao.cn #redis
    port: 6379
    password: 123456
  lettuce:
    pool:
      max-active: 8   #连接池最大连接数（使用负值表示没有限制）默认8
      max-wait: -1   #连接池最大阻塞等待时间（使用负值表示没有限制）默认-1
      max-idle: 8   #连接池中的最大空闲连接默认8
      min-idle: 0  #连接池中的最小空闲连接默认0